### ISSUE TITLE
crash server 1.18.1

### ISSUE THREAD

**Issue by laboriens** [woo200/forgetranslator#1]
forge 1.18.1 39.0.79
AutoTranslate-v1.0.0.jar

crash: https://textup.fr/613978dE

your mod crashes the server on startup

**Comment by woo200** [comment]
This is a client side only mod. If you have it in a modpack, remove it from the server side, and only use it client side.

**Comment by laboriens** [comment]
except that if I delete it on the server side the client cannot join the server it is rejected because it has the mods which is not on the server

**Comment by woo200** [comment]
I'll look into it, and update the mod once it is done.

**Comment by woo200** [comment]
I can't recreate this issue, can you remove the mod from the server side, try to join, and send me the error message?

**Comment by laboriens** [comment]
sorry I think it's actually a curseforge bug I'll try again and I'll let you know

**Comment by laboriens** [comment]
is repared
