### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by NicolasLasch** [woo200/forgetranslator#3]
Is there a way to use the mod for 1.18.2 ? Thank you :)

**Comment by woo200** [comment]
https://www.curseforge.com/minecraft/mc-mods/automatic-chat-translator/files/all?page=1&pageSize=20&version=1.18.1

This is 1.18.1, but it will probably work, if it doesn't, I can release a version for. 1.18.2.

**Comment by NicolasLasch** [comment]
> https://www.curseforge.com/minecraft/mc-mods/automatic-chat-translator/files/all?page=1&pageSize=20&version=1.18.1
> 
> This is 1.18.1, but it will probably work, if it doesn't, I can release a version for. 1.18.2.

Thank you, I'll try and tell you about it :)
